### ISSUE TITLE
Добавить рестарт игры через кнопку 

### ISSUE THREAD

**Issue by HolikAliaksandr** [maries-you/tetris#11]
Можно сделать простую кнопку (например с конкретной id). а там уже отдельно можно будет эту кнопку перенести на другую, более красивую

**Comment by HolikAliaksandr** [comment]
Реализовано. Появится со следующим билдом. (вместе с показом следующей фигуры)

**Comment by thehighestmath** [comment]
Рестарт игры не перезапускает если проиграно
Задача открыта
