### ISSUE TITLE
Адаптация страницы

### ISSUE THREAD

**Issue by Patsy555** [maries-you/tetris#17]
При нажатии клавиши "Вниз", фигура опускается вниз вместе со страницей браузера. При нажатии клавиши "Вверх" фигура поворачивается, а страница браузера поднимается вверх. 

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Откройте файл "game.html" в браузере Google Chrome
2. Нажмите на кнопку "Вниз".
3. Нажмите на кнопку "Вверх".

**Ожидаемое поведение**
При нажатии кнопки "Вниз" фигура опустится вниз, расположение поля на странице браузера остается неизменным. При нажатии кнопки "Вверх" фигура повернется, расположение поля на странице браузера остается неизменным.

https://github.com/maries-you/tetris/assets/131196769/d8a9bae0-86e9-437d-a848-7a6936594f3f

** Скриншоты**
Адаптация страницы

**Comment by HolikAliaksandr** [comment]
Нужно проверить на верстку мою последнюю "версию". У меня все гут

**Comment by Patsy555** [comment]
А где взять последнею версию?

**Comment by thehighestmath** [comment]
Стаять!
Тестер проверяет последний релиз (в нашей ситуации это мастер/мэйн)
То, что у тебя, Саша, в ветке всё это -- это замечательно) Но её надо поправить, чтобы CI прошёл и тогда уже можно подумывать, чтобы обновить главную ветку, которую можно тестировать:)

**Comment by HolikAliaksandr** [comment]
А как теперь страничка отображается? Пока может баг прикрыть?

**Comment by thehighestmath** [comment]
Выглядит как будто именно это решено
