### ISSUE TITLE
Отображение фигур вверху поля тетриса

### ISSUE THREAD

**Issue by Patsy555** [maries-you/tetris#18]
Фигуры отображаются некорректно вверху поля тетриса.

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Открыть файл "game.html" в браузере Google Chrome
2. Нажмите на кнопку "вниз".
3. Заполните поля тетриса фигурами доверху

**Ожидаемое поведение**
При заполнении фигурами поля тетриса доверху, последняя фигура будет отображаться корректно

** Скриншоты**
Если применимо, добавьте скриншоты, которые помогут объяснить вашу проблему.
![Отображение фигур вверху поля тетрис](https://github.com/maries-you/tetris/assets/131196769/e15b8579-5643-4eb5-9221-840cd2bbd6cc)

**Comment by HolikAliaksandr** [comment]
Тут део в том, что алгоритм отрисовки фигуры, когда фигура не вся отрисована, считает "крайней" (или точной опоры) последний элемент фигуры. поэтому такие баги я часто встречал в разных играх "тетрис"
