### ISSUE TITLE
Выход фигуры за пределы поля тетриса

### ISSUE THREAD

**Issue by Patsy555** [maries-you/tetris#19]
**Опишите ошибку (баг)**
После того как первая фигура опустилась вниз поля тетриса, следующая фигура покидает поле тетриса

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Открыть файл "game.html" в браузере Google Chrome
2. Нажмите на кнопку "Вниз".
3. Нажмите и задержите кнопку "Вправо"

**Ожидаемое поведение**
Фигура не выйдет за поле тетриса

** Скриншоты**

https://github.com/maries-you/tetris/assets/131196769/623b0802-1e1d-4857-8819-d156d78f057d

**Comment by Patsy555** [comment]
Аналогичный дефект при нажатии клавиши "Влево"

**Comment by HolikAliaksandr** [comment]
Пока фигура вся не отрисована - ее граница взаимодействия отсутствует. Алгоритм не выпускает за пределы поля только полностью отрисованную фигуру.
