### ISSUE TITLE
Реализовать сложность игры

### ISSUE THREAD

**Issue by thehighestmath** [maries-you/tetris#20]
**Текущее состояние:**
- Всегда появляется пустой стакан

**Ожидаемое состояние:**
- При выборе 0-го уровня сложности -- появляется пустой стакан
- При выборе 1-го уровня сложности -- стакан с частино заполненой одной строкой
- При выборе 2-го уровня сложности -- стакан с частино заполнеными двумя строками
- При выборе n-го уровня сложности -- стакан с частино заполнеными N строками

**Comment by HolikAliaksandr** [comment]
Сколько максимум уровней делать?

**Comment by thehighestmath** [comment]
Это почти неважно. Пусть будет пока с нулевого по третий уровень
