### ISSUE TITLE
Кнопка "Рестарт tetris"

### ISSUE THREAD

**Issue by Patsy555** [maries-you/tetris#22]
**Опишите ошибку (баг)**
При нажатии кнопки "Рестарт tetris" ничего не происходит

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Запустить игру
2. Заполнить поле тетриса фигурами доверху
3. В выпадающем окне !game over! нажать кнопку "OK"
4. Нажать кнопку "Рестарт tetris"

**Ожидаемое поведение**
Окно тетриса обновиться, можно играть заново

** Скриншоты**

https://github.com/maries-you/tetris/assets/131196769/c83f2f5d-6e41-44a0-9a84-fd5d68113134

**Дополнительный контекст**
Аналогичный баг в браузере Firefox

**Comment by thehighestmath** [comment]
Функциональность этой кнопки **не** заявлялась. Задача пока не выполнена. Бага нет. Это заглушка.
