### ISSUE TITLE
Цвет выпадающей фигуры не совпадает с цветом в окне "Следующая фигура"

### ISSUE THREAD

**Issue by AndreKrep** [maries-you/tetris#24]
Цвет выпадающей фигуры не совпадает с цветом в окне "Следующая фигура"

Шаги по воспроизведению поведения:
1. Откройте файл "game.html" в браузере Google Chrome.
2. В окне "Следующая фигура" появляется фигура окрашенная фигура

Ожидаемое поведение:

Цвет появляющейся фигуры совпадает с цветом фигуры, анонсированной в окне "Следующая фигура"

**Дополнительный контекст**
Добавьте сюда любой другой контекст, касающийся проблемы.

https://github.com/maries-you/tetris/assets/119307014/1349d90e-d4be-4202-ae6c-b66f18d7f411

**Comment by HolikAliaksandr** [comment]
Этот баг уйдет как только каждая фигура будет иметь свой цвет.

**Comment by HolikAliaksandr** [comment]
Баг исправлен
