### ISSUE TITLE
Сделать ускорение игры

### ISSUE THREAD

**Issue by thehighestmath** [maries-you/tetris#5]
При наборе определённого количества очков/убранных линий надо повышать скорость игры

**Comment by HolikAliaksandr** [comment]
Реализовано ускорение игры как через кнопки, так и автоматически (каждые 5 очков, но до 20. после 20 скорость не меняется - и так максимальная)

**Comment by thehighestmath** [comment]
А где код?)

**Comment by thehighestmath** [comment]
Вернее пулл реквест надо открыть
Буду потом ревьювить))

**Comment by HolikAliaksandr** [comment]
Ускорение игры реализовано!

**Comment by thehighestmath** [comment]
Нене, закроем как вмерждим код, пока он на ревью)
