### ISSUE TITLE
Доска почёта

### ISSUE THREAD

**Issue by thehighestmath** [maries-you/tetris#6]
ТОП-5/10/20 игроков по набранным очкам

**Comment by HolikAliaksandr** [comment]
Для доски почета сперва нужно реализовать перезапуск игры с кнопки.

**Comment by thehighestmath** [comment]
Я не считаю, что нужен перезапуск с кнопки для этой задачи

В моем видении таблица рекордов должна храниться в браузере и даже спустя день мой рекорд должен оставаться в ней (пусть я и перезагружал веб страницу)

Ref:https://learn.javascript.ru/localstorage

**Comment by thehighestmath** [comment]
Было разработано решение получше
https://github.com/maries-you/tetris/issues/15
