### ISSUE TITLE
Давать очки за ускоренное перемешение фигуры

### ISSUE THREAD

**Issue by thehighestmath** [maries-you/tetris#79]
- за стрелку вниз
- за пробел

**Comment by Dokker32** [comment]
Сделал так чтобы давалось очко за нажатие пробела и стрелки вниз, но со стрелкой вниз не совсем понятно правильно ли это давать очки за единичное нажатие или нужно давать очки за зажатие в течении определенного времени, или только когда оно коснется дна или вообще не давать очки за это ?

**Comment by thehighestmath** [comment]
Скорее всего надо давать на 1 поинт, а 0.1, но об этом я ещё подумаю

**Comment by Dokker32** [comment]
Ну тогда пока сделаю так , за каждое нажатие 0.1

**Comment by Dokker32** [comment]
#100
